name: IPTV Channel Aggregator # 工作流的名称，在 GitHub Actions 页面会显示

on:
  workflow_dispatch: # 允许在 GitHub Actions 界面手动触发此工作流
  schedule:
    - cron: '0 * * * *' # 定时任务：每小时的第0分钟运行（即每小时运行一次）。
                        # 你可以根据需要调整这个 cron 表达式。
                        # 例如：'0 0 * * *' 每天午夜运行一次。
                        # cron 表达式的格式：分钟 小时 日 月 星期 (都用UTC时间)

jobs:
  aggregate-iptv-channels:
    runs-on: ubuntu-latest # 指定工作流运行的操作系统环境，这里使用最新的 Ubuntu 虚拟机

    steps:
    - name: Checkout repository # 步骤1：检出你的 GitHub 仓库代码
      uses: actions/checkout@v4 # 使用官方的 checkout action 来获取仓库内容
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 进行认证
        fetch-depth: 0 # 获取完整历史记录

    - name: List files for debugging # 步骤2 (可选，用于调试)：列出仓库中的所有文件和目录
      # 如果你遇到文件找不到的问题（例如 `ENOENT` 错误），这个步骤可以帮助你确认文件结构。
      # 确认 `requirements.txt` 和 `main.py` 是否在预期路径。
      run: ls -R

    - name: Set up Python # 步骤3：设置 Python 运行环境
      uses: actions/setup-python@v4 # 使用官方的 setup-python action
      with:
        python-version: '3.11' # 指定使用的 Python 版本

    - name: Install dependencies # 步骤4：安装 Python 依赖
      # pip 默认会查找当前目录下的 requirements.txt 文件
      run: pip install -r requirements.txt
      working-directory: ./ # <-- **重要：** 确保这个路径是 `requirements.txt` 所在的目录
                            # 如果 `requirements.txt` 在仓库根目录，用 `./`
                            # 如果在子目录（例如 `my-app/`），请改为 `./my-app/`

    - name: Run IPTV Channel Aggregator # 步骤5：运行IPTV频道聚合脚本
      run: python main.py
      working-directory: ./ # <-- **重要：** 确保这个路径是 `main.py` 所在的目录
                            # 如果 `main.py` 在仓库根目录，用 `./`
                            # 如果在子目录（例如 `my-app/`），请改为 `./my-app/`

    - name: Commit test results # 步骤6：将测试结果文件提交回仓库
      # 这段脚本将配置 Git 用户信息，添加并提交测试结果文件，然后推送到远程仓库。
      # `[skip ci]` 标签会避免本次提交再次触发这个工作流，防止无限循环。
      run: |
        git config user.name "github-actions[bot]" # 配置 Git 用户名，使用 GitHub 提供的机器人用户
        git config user.email "github-actions[bot]@users.noreply.github.com" # 配置 Git 邮箱
        
        # 确保在 main 分支上
        git checkout main
        
        # 创建必要的目录（如果不存在）
        mkdir -p 地方频道
        mkdir -p 频道模板
        
        # 添加所有可能的测试结果文件到 Git 暂存区
        git add iptv.txt 2>/dev/null || true
        git add iptv_speed.txt 2>/dev/null || true
        git add unmatched_channels.txt 2>/dev/null || true
        git add iptv_list.txt 2>/dev/null || true
        
        # 添加地方频道目录中的所有文件
        git add 地方频道/*.txt 2>/dev/null || true
        
        # 添加频道模板目录中的所有文件
        git add 频道模板/*.txt 2>/dev/null || true
        
        # 显示当前状态
        echo "=== Git Status ==="
        git status
        
        echo "=== Staged Files ==="
        git diff --cached --name-only || echo "No staged files"
        
        # 检查是否有文件被添加到暂存区
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          # 提交更改
          git commit -m "Update IPTV test results [skip ci]"
          git push origin main # 明确推送到 main 分支
          echo "Changes committed and pushed to main branch"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub 自动提供的令牌，用于认证 Git 操作 
